### ISSUE TITLE
Mod Suggestion - Never Depleting Summon Pool for AI

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [julian-perge/InscryptionMods#5]
One thing that confuses me is that the AI eventually just stops summoning things. Is there a way to fix that?

**Comment by julian-perge** [comment]
There is actually!

The class is `Opponent` and the method that determines if they keep playing cards is `QueueNewCards`.

There's a conditional check `if(this.NumTurnsTaken < this.TurnPlan.Count)`, so that if the number of turns taken is greater than or equal to the number of plans (what cards will be queued), then the opponent will no longer play cards.

**Comment by P3rf3ctXZer0** [comment]
nice since I don't code I assume it will be easy for you. I without pressuring you will keep an open eye. Lost one of em to leshy :3

**Comment by julian-perge** [comment]
> nice since I don't code I assume it will be easy for you. I without pressuring you will keep an open eye. Lost one of em to leshy :3

Here you go! https://github.com/julian-perge/InscryptionMods/tree/main/Events/OpponentsNeverStopPlayingCards

**Comment by P3rf3ctXZer0** [comment]
Nice thank you :D best new years now I can suffer 100% of the time instead of 90% - (totally not a masochist)
